// src/components/Reviews/ReviewModal.vue
<template>
  <div class="fixed overflow-hidden z-10 inset-0" v-show="showReviews">
    <div
      class="
        flex
        items-end
        justify-center
        min-h-screen
        pt-4
        px-4
        pb-20
        text-center
        sm:block sm:p-0
        overflow-hidden
      "
    >
      <div class="fixed inset-0 transition-opacity" aria-hidden="true">
        <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
      </div>

      <!-- This element is to trick the browser into centering the modal contents. -->
      <span
        class="hidden sm:inline-block sm:align-middle sm:h-screen"
        aria-hidden="true"
        >&#8203;</span
      >

      <div
        class="
          inline-block
          align-bottom
          bg-white
          rounded-lg
          text-left
          overflow-hidden
          shadow-xl
          transform
          transition-all
          sm:my-8 sm:align-middle sm:max-w-lg sm:w-full
        "
        role="dialog"
        aria-modal="true"
        aria-labelledby="modal-headline"
      >
        <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
          <div class="sm:flex sm:items-start justify-between">
            <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
              <h3
                class="text-lg leading-6 font-medium text-gray-900"
                id="modal-headline"
              >
                Reviews for {{ item.name }}
              </h3>
            </div>
            <button
              type="button"
              @click="closeModal()"
              class="
                focus:outline-none focus:ring-2
                ring-secondary ring-offset-8
                rounded-sm
                hover:fill-black
                fill-current
              "
            >
              <svg
                class="h-4"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="gray"
                aria-hidden="true"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="3"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
          <div
            class="
              mt-2
              flex-row
              grid-cols-1
              xl:h-2xl
              md:h-96
              overflow-auto
              mb-20
            "
          >
            <!-- <error-display :error="error" :show="showError"></error-display>
            <square-spinner :loading="loading"></square-spinner> -->
            <div v-if="!showError">
              <div v-if="hasReviews">
                <review-card
                  v-for="review in reviews"
                  v-bind:key="review.id"
                  :review="review"
                />
              </div>
              <div v-if="!hasReviews && !loading">
                <div class="flex max-w-7xl" data-aos="fade-up">
                  <div class="pt-5 sm:pl-9">
                    <div
                      class="
                        max-w-sm
                        w-96
                        rounded-lg
                        overflow-hidden
                        shadow-lg
                        bg-white
                        border-2
                      "
                    >
                      <div class="px-4 py-4">
                        <h1 class="text-xl">No reviews for this item</h1>
                        <p class="text-gray-500 text-md">
                          You can submit one on the store page
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          class="
            bg-gray-50
            px-4
            py-3
            sm:px-6 sm:flex sm:flex-row-reverse
            absolute
            inset-x-0
            bottom-0
          "
        >
          <button
            type="button"
            @click="closeModal()"
            class="
              mt-3
              w-full
              inline-flex
              justify-center
              rounded-md
              cursor-pointer
              px-5
              py-2
              shadow-lg
              bg-gray-50
              text-secondary
              font-semibold
              tracking-wider
              border-4 border-secondary
              transform
              transition
              hover:-translate-y-0.5
              hover:bg-secondary-superlight
              focus:-translate-y-0.5
              focus:outline-none
              focus:ring
              focus:ring-offset-1
              focus:ring-primary
              active:-translate-y-0.5
              sm:ml-3 sm:w-auto
            "
          >
            Close
          </button>
          <button
            type="button"
            @click="openReviewForm()"
            class="
              mt-3
              w-full
              inline-flex
              justify-center
              rounded-md
              sm:ml-3 sm:w-auto
              cursor-pointer
              px-5
              py-3
              shadow-lg
              bg-primary
              font-semibold
              tracking-wider
              transform
              transition
              hover:-translate-y-0.5 hover:bg-primary-dark
              focus:-translate-y-0.5
              focus:outline-none
              focus:ring
              focus:ring-offset-1
              focus:ring-secondary
              active:bg-primary-light
            "
          >
            Write a review
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ReviewCard from "../../components/Reviews/ReviewCard.vue";

export default {
  name: "ReviewModal",
  props: {
    showReviews: Boolean,
    hasReviews: Boolean,
    reviews: Array,
    item: Object,
    showError: Boolean,
    error: Object,
    loading: Boolean,
  },
  components: {
    ReviewCard,
  },
  data() {
    return {};
  },
  methods: {
    closeModal() {
      this.$emit("close");
    },
    openReviewForm() {
      this.$router.push({
        name: `ReviewForm`,
        params: {
          item: this.item.id,
        },
      });
    },
  },
};
</script>

// src/components/reviews/ReviewModal.jsx
import { useState } from 'react'

import ReviewList from './ReviewList'
import reviews from '../../assets/reviews.json'

function ReviewModal() {
  const [open, setOpen] = useState(true)

  function handleClose() {
    setOpen(!open)
  }

  return (
    <>
      {!open ? null :
        <div className="fixed overflow-hidden z-10 inset-0 max-h-screen h-auto">
          <div className="flex items-end justify-center pt-4 px-4 pb-20 text-center sm:block sm:p-0 overflow-hidden">
            <div className="fixed inset-0 transition-opacity" aria-hidden="true">
              <div className="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>

            <span className="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

            <div className="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full" role="dialog" aria-modal="true" aria-labelledby="modal-headline">
              <div className="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                <div className="sm:flex sm:items-start justify-between">
                  <div className="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                    <h3 className="text-lg leading-6 font-medium text-gray-900" id="modal-headline">
                      Reviews for
                    </h3>
                  </div>
                  <button type="button" onClick={handleClose} className="focus:outline-none focus:ring-2 ring-secondary ring-offset-8 rounded-sm hover:fill-black fill-current">
                    <svg className="h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="gray" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
                {/* <div className="mt-2 flex-row grid-cols-1 xl:h-2xl md:h-96 overflow-auto mb-20"> */}
                {/* <error-display :error="error" :show="showError"></error-display>
      <square-spinner :loading="loading"></square-spinner> */}
                <div v-if="!showError">
                  <div v-if="hasReviews">
                    <ReviewList reviews={reviews} />
                  </div>
                  {/* <div v-if="!hasReviews && !loading">
        <div className="flex max-w-7xl" data-aos="fade-up">
          <div className="pt-5 sm:pl-9">
            <div className="max-w-sm w-96 rounded-lg overflow-hidden shadow-lg bg-white border-2">
              <div className="px-4 py-4">
                <h1 className="text-xl">No reviews for this item</h1>
                <p className="text-gray-500 text-md">
                  You can submit one on the store page
                </p>
              </div>
            </div>
          </div> */ }
                </div>
              </div>
            </div>
          </div>
        </div>
      }
    </>
  )
}

export default ReviewModal
